return {
	symbolMap = {
		DEBUG = '', -- 
		ERROR = '', -- 
		INFO = '', -- 
		TRACE = '',
		WARN = '', -- 
		OTHER = '',
		HINT = '',
		LOCK = '',
		BRANCH = '',
		INSTALLED = '',
		UNINSTALLED = '',
		PENDING = '',
		MID_DOT = '•',
		RENAMED = '',
		DELETED = '', -- '✖'
		ADDED = '✚', -- '✚'
		MODIFIED = '',
		GIT_UNTRACKED = '',
		GIT_STAGED = '',
		GIT_IGNORED = '',
		GIT_UNSTAGED = '*',
		GIT_CONFLICT = '',
		BOOKMARK = '笠',
		BOOKMARK_ANNOTATION = 'ﰠ',
		ARROW_UP = '↑',
		ARROW_DOWN = '↓',
		ARROW_LEFT = '←',
		ARROW_RIGHT = '→',
		EXPANDED = '▾',
		COLLAPSED = '▸',
		EXPANDED_L = '',
		COLLAPSED_L = '',
	},

	kindSymbolMap = {
		Array = '',
		Boolean = '◩',
		Class = 'ﴯ',
		Collapsed = '',
		Color = '',
		Constant = '🄲',
		Constructor = '',
		Enum = '',
		EnumMember = '',
		Event = '',
		Field = '', -- 'ﰠ',
		File = '',
		Folder = '',
		Function = '',
		Interface = '', -- ''
		Keyword = '',
		Method = '',
		Module = '',
		Namespace = '',
		Null = '∅',
		Number = '',
		Object = '',
		Operator = '',
		Package = '',
		Property = '',
		Reference = '',
		Snippet = '',
		String = '',
		Struct = 'פּ',
		Text = '',
		TypeParameter = '𝕋', -- ''
		Unit = '塞',
		Variable = '𝕍', -- '', '𝒗'
	},
}
